
export interface PublicTalk {
    number: number | string;
    theme: string;
}

export const publicTalks: PublicTalk[] = [
    { number: 1, theme: "Comment la Bible peut vous aider à améliorer votre vie" },
    { number: 2, theme: "La Bible nous aide-t-elle à faire face aux problèmes d’aujourd’hui ?" },
    { number: 3, theme: "La Bible : un livre digne de confiance" },
    { number: 4, theme: "Ce que la Bible prédit pour notre époque" },
    { number: 5, theme: "Le Royaume de Dieu est-il une réalité ?" },
    { number: 6, theme: "Comment le Royaume de Dieu nous sera bénéfique" },
    { number: 7, theme: "Vivre en accord avec la prière modèle" },
    { number: 8, theme: "Servez Jéhovah d’un cœur complet" },
    { number: 9, theme: "La voie de Dieu est la meilleure" },
    { number: 10, theme: "Appréciez-vous les dons que Dieu vous a faits ?" },
    { number: 11, theme: "Ce qui se cache derrière l’esprit de rébellion" },
    { number: 12, theme: "Respectons l’autorité divine" },
    { number: 13, theme: "Une bonne nouvelle dans un monde violent" },
    { number: 14, theme: "Menez une vie de famille qui honore Dieu" },
    { number: 15, theme: "Qui est votre Dieu ?" },
    { number: 16, theme: "Avons-nous des raisons de croire en Dieu ?" },
    { number: 17, theme: "Honorez Dieu dans tout ce que vous faites" },
    { number: 18, theme: "Les principes bibliques peuvent-ils nous aider à affronter les problèmes actuels ?" },
    { number: 19, theme: "La vie a-t-elle un sens ?" },
    { number: 20, theme: "Le Créateur : comprenez-le, aimez-le" },
    { number: 21, theme: "Le monde actuel survivra-t-il ?" },
    { number: 22, theme: "L’avenir de la religion" },
    { number: 23, theme: "Le jour du jugement : une raison d’avoir peur ou d’espérer ?" },
    { number: 24, theme: "Un seul vrai Dieu, une seule vraie foi : est-ce possible ?" },
    { number: 25, theme: "Pourquoi les chrétiens doivent-ils être différents ?" },
    { number: 26, theme: "Vous pouvez vivre éternellement sur la terre. Le croyez-vous ?" },
    { number: 27, theme: "Une terre purifiée sera-t-elle un jour une réalité ?" },
    { number: 28, theme: "De bonnes relations avec les autres : comment est-ce possible ?" },
    { number: 29, theme: "Comment faire face aux inquiétudes de la vie" },
    { number: 30, theme: "Comment bâtir un mariage solide et heureux" },
    { number: 31, theme: "Parents, bâtissez avec sagesse" },
    { number: 32, theme: "Comment améliorer la communication au sein de la famille" },
    { number: 33, theme: "L’alcool : quel est le point de vue équilibré ?" },
    { number: 34, theme: "Faites confiance au Dieu de tout réconfort" },
    { number: 35, theme: "Comment trouver la sécurité dans un monde dangereux" },
    { number: 36, theme: "Est-ce plus tard que vous ne le pensez ?" },
    { number: 37, theme: "Dieu se soucie-t-il vraiment de vous ?" },
    { number: 38, theme: "Comment pouvez-vous survivre à la fin du monde ?" },
    { number: 39, theme: "Les décisions que vous prenez ont une influence sur votre avenir" },
    { number: 40, theme: "Ce que signifie aimer son prochain" },
    { number: 41, theme: "Agissez avec sagesse à l’approche de la fin" },
    { number: 42, theme: "Comment l’amour et la foi peuvent vaincre le monde" },
    { number: 43, theme: "Le chemin qui mène à la vie est-il trop difficile ?" },
    { number: 44, theme: "Ayez confiance dans le pouvoir de la Parole de Dieu" },
    { number: 45, theme: "Suivez l’exemple du plus grand homme qui ait vécu" },
    { number: 46, theme: "Jésus Christ : qui est-il vraiment ?" },
    { number: 47, theme: "« Soyez saints parce que je suis saint »" },
    { number: 48, theme: "Rejetons les raisonnements qui sont contre la connaissance de Dieu" },
    { number: 49, theme: "Le seul remède à la défaillance des humains" },
    { number: 50, theme: "Qui est qualifié pour diriger l’humanité ?" },
    { number: 51, theme: "La présence du Christ : que signifie-t-elle pour vous ?" },
    { number: 52, theme: "Dieu et votre foi : quel lien ?" },
    { number: 53, theme: "Une fraternité mondiale sauvée de la destruction" },
    { number: 54, theme: "Le règne millénaire de paix de Dieu est proche" },
    { number: 55, theme: "La paix et la sécurité véritables : quand ?" },
    { number: 56, theme: "Où trouver de l’aide en temps de détresse ?" },
    { number: 57, theme: "Dans les difficultés, où trouver du réconfort ?" },
    { number: 58, theme: "Qui peut être sauvé ?" },
    { number: 59, theme: "Vous serez libérés !" },
    { number: 60, theme: "Comment la sagesse divine nous est bénéfique" },
    { number: 61, theme: "Qui sont les vrais disciples du Christ ?" },
    { number: 62, theme: "Le rôle de la religion dans les affaires du monde" },
    { number: 63, theme: "Ne vous laissez pas tromper" },
    { number: 64, theme: "Qui est le seul à pouvoir nous guider ?" },
    { number: 65, theme: "L’heure de rendre des comptes à Dieu est proche" },
    { number: 66, theme: "Quand Dieu va-t-il commencer à diriger le monde ?" },
    { number: 67, theme: "Pourquoi se réfugier en Jéhovah ?" },
    { number: 68, theme: "Quel est le fondement de votre espérance ?" },
    { number: 69, theme: "La résurrection : une victoire sur la mort !" },
    { number: 70, theme: "Que deviendront les morts ?" },
    { number: 71, theme: "Restez spirituellement éveillés" },
    { number: 72, theme: "L’amour : la qualité qui distingue les vrais chrétiens" },
    { number: 73, theme: "Comment se faire un bon nom auprès de Dieu" },
    { number: 74, theme: "Comment avoir une bonne conscience" },
    { number: 75, theme: "Combien de temps vous reste-t-il ?" },
    { number: 76, theme: "La paix véritable viendra-t-elle un jour ?" },
    { number: 77, theme: "Dans quel genre de personnes Dieu trouve-t-il son plaisir ?" },
    { number: 78, theme: "Dieu se souvient de vous. Et vous ?" },
    { number: 79, theme: "L’amitié avec Dieu ou l’amitié avec le monde : laquelle choisirez-vous ?" },
    { number: 80, theme: "Pourquoi vous pouvez avoir confiance en la Bible" },
    { number: 81, theme: "Ce que notre Créateur attend de nous" },
    { number: 82, theme: "Jéhovah et Christ : sont-ils égaux ?" },
    { number: 83, theme: "Vous pouvez connaître le bonheur dès maintenant !" },
    { number: 84, theme: "Peut-on aimer la justice et haïr l’injustice ?" },
    { number: 85, theme: "Bonne nouvelle pour toutes les nations" },
    { number: 86, theme: "Changements sur la terre : quel avenir ?" },
    { number: 87, theme: "Qui sont les ministres de Dieu aujourd’hui ?" },
    { number: 88, theme: "« Tenez-vous prêts » !" },
    { number: 89, theme: "Pourquoi les humains ont besoin de Dieu" },
    { number: 90, theme: "La vie dans le nouveau monde de Dieu" },
    { number: 91, theme: "Pourquoi vivre selon les normes de la Bible ?" },
    { number: 92, theme: "Le culte qui plaît à Dieu" },
    { number: 93, theme: "Des prières qui sont exaucées" },
    { number: 94, theme: "Dieu condamne-t-il toutes les religions ?" },
    { number: 95, theme: "Que se passe-t-il après la mort ?" },
    { number: 96, theme: "La science a-t-elle rendu la Bible inutile ?" },
    { number: 97, theme: "Comment trouver la joie de vivre" },
    { number: 98, theme: "Qui est le Diable ? Est-il réel ?" },
    { number: 99, theme: "La résurrection : pourquoi cette espérance est sûre" },
    { number: 100, theme: "Comment surmonter le mal par le bien" },
    { number: 101, theme: "Jéhovah : le Grand Potier" },
    { number: 102, theme: "Choisissez la vie !" },
    { number: 103, theme: "Vous pouvez être aussi justes que Dieu" },
    { number: 104, theme: "Parents, êtes-vous un bon exemple ?" },
    { number: 105, theme: "Enfants, quelle est votre place dans les dispositions de Dieu ?" },
    { number: 106, theme: "Comment l’esprit saint agit sur nous" },
    { number: 107, theme: "Soumettons-nous à la domination de Dieu dès maintenant" },
    { number: 108, theme: "La scène de ce monde est en train de changer" },
    { number: 109, theme: "L’hospitalité : une marque du christianisme" },
    { number: 110, theme: "Dieu vient en aide à ceux qui l’aiment" },
    { number: 111, theme: "La confiance en l’organisation de Jéhovah" },
    { number: 112, theme: "Comment montrer du respect pour nos lieux de culte" },
    { number: 113, theme: "Comment affronter l’avenir avec foi et courage" },
    { number: 114, theme: "Appréciez votre place dans l’assemblée" },
    { number: 115, theme: "Comment vous protéger du piège du Diable : le spiritisme" },
    { number: 116, theme: "Le mariage : son origine et son but" },
    { number: 117, theme: "Comment faire pour que votre mariage soit une réussite durable" },
    { number: 118, theme: "Imitez le Dieu de vérité" },
    { number: 119, theme: "La jalousie : comment la maîtriser ?" },
    { number: 120, theme: "Comment trouver le bonheur en faisant des dons" },
    { number: 121, theme: "Un peuple pur et droit aux yeux de Jéhovah" },
    { number: 122, theme: "Le contentement favorise la piété" },
    { number: 123, theme: "Pourquoi les chrétiens doivent être des porteurs de lumière" },
    { number: 124, theme: "Résistez à la tendance à vous plaindre" },
    { number: 125, theme: "Marcher avec Dieu apporte des bienfaits, aujourd’hui et pour toujours" },
    { number: 126, theme: "Continuez de grandir en spiritualité" },
    { number: 127, theme: "Comment rester spirituellement fort" },
    { number: 128, theme: "Votre avenir : comment l’assurer ?" },
    { number: 129, theme: "Restez intègres dans un monde méchant" },
    { number: 130, theme: "Les principes bibliques : pouvons-nous vivre en les appliquant ?" },
    { number: 131, theme: "Comment endurer la persécution" },
    { number: 132, theme: "Comment garder son zèle pour le vrai culte" },
    { number: 133, theme: "Qui sèmera le vent récoltera la tempête" },
    { number: 134, theme: "Un monde sans préjugés : quand ?" },
    { number: 135, theme: "Comment garder une vision positive de la vie" },
    { number: 136, theme: "La vraie liberté : où la trouver ?" },
    { number: 137, theme: "Ce que Dieu a fait pour vous" },
    { number: 138, theme: "Êtes-vous conscient de vos besoins spirituels ?" },
    { number: 139, theme: "La miséricorde : une facette dominante de la personnalité de Dieu" },
    { number: 140, theme: "Vivez une vie qui a un but" },
    { number: 141, theme: "Gardez l’esprit de sacrifice" },
    { number: 142, theme: "Regardez le mariage du point de vue de Dieu" },
    { number: 143, theme: "Appréciez-vous le rôle du Christ dans le projet de Dieu ?" },
    { number: 144, theme: "Quel genre de nom vous faites-vous ?" },
    { number: 145, theme: "Qu’est-ce que le Royaume de Dieu ?" },
    { number: 146, theme: "Utilisez l’éducation pour louer Jéhovah" },
    { number: 147, theme: "Trouvez du plaisir dans la justice de Jéhovah" },
    { number: 148, theme: "La création révèle le Dieu vivant" },
    { number: 149, theme: "Amis de la paix, réjouissez-vous !" },
    { number: 150, theme: "Êtes-vous sur le chemin de la vie éternelle ?" },
    { number: 151, theme: "Jéhovah est un refuge pour son peuple" },
    { number: 152, theme: "L’homme qui a ruiné la réputation de Dieu" },
    { number: 153, theme: "Qui est comme Jéhovah notre Dieu ?" },
    { number: 154, theme: "Les anges : quelle est leur influence sur notre vie ?" },
    { number: 155, theme: "Fin des ténèbres, un monde de lumière" },
    { number: 156, theme: "« Un temps pour tout »" },
    { number: 157, theme: "Le point de vue de Dieu sur les relations sexuelles et le mariage" },
    { number: 158, theme: "Restons sans tache dans un monde dépravé" },
    { number: 159, theme: "Regardons les jeunes d’un œil positif" },
    { number: 160, theme: "Comment vous pouvez vous approcher de Dieu" },
    { number: 161, theme: "Pourquoi Jésus a-t-il souffert et est-il mort ?" },
    { number: 162, theme: "Sommes-nous en train de gagner le combat pour la pureté de la pensée et de la conduite ?" },
    { number: 163, theme: "Pourquoi craindre le vrai Dieu ?" },
    { number: 164, theme: "Dieu est-il responsable de nos malheurs ?" },
    { number: 165, theme: "La domination de l’homme est à son point de rupture" },
    { number: 166, theme: "Appréciez la vie en abondance dès maintenant !" },
    { number: 167, theme: "Ce que la proximité d’Armaguédon signifie pour vous" },
    { number: 168, theme: "Rendez à Dieu ce qui est à Dieu" },
    { number: 169, theme: "Pourquoi Jésus est le seul sauveur de l’humanité" },
    { number: 170, theme: "Soyez courageux et ayez confiance en Jéhovah" },
    { number: 171, theme: "Le gouvernement mondial de Dieu : une réalité" },
    { number: 172, theme: "Quel espoir pour nos chers disparus ?" },
    { number: 173, theme: "Le plus grand miracle de tous les temps" },
    { number: 174, theme: "Le seul vrai Dieu" },
    { number: 175, theme: "Quelles sont les références des vrais chrétiens ?" },
    { number: 176, theme: "Bienvenue dans la seule communauté internationale qui soit unie" },
    { number: 177, theme: "Quel est votre point de vue sur l’autorité ?" },
    { number: 178, theme: "Comment le Royaume de Dieu nous touche-t-il aujourd’hui ?" },
    { number: 179, theme: "Une bonne nouvelle pour tous les peuples" },
    { number: 180, theme: "La Bible et votre avenir" },
    { number: 181, theme: "Un monde nouveau et juste est proche" },
    { number: 182, theme: "Les jeunes peuvent-ils rendre Dieu heureux ?" },
    { number: 183, theme: "La mort n’est pas la fin de tout !" },
    { number: 184, theme: "La fin des fausses religions est proche" },
    { number: 185, theme: "Que se passe-t-il quand on meurt ?" },
    { number: 186, theme: "Une prière qui sera exaucée" },
    { number: 187, theme: "Comment être un bon père" },
    { number: 188, theme: "Ce que l’avenir nous réserve" },
    { number: 189, theme: "Pourquoi se faire baptiser ?" },
    { number: 190, theme: "Qui est ton Dieu ?" },
    { number: 191, theme: "Comment faire face à l’avenir en toute confiance" },
    { number: 192, theme: "Comment surmonter l’inquiétude" },
    { number: 193, theme: "Comment trouver la paix intérieure" },
    { number: 194, theme: "Comment renforcer votre confiance en Dieu" },
];
